# Generated by Django 3.2.19 on 2023-06-09 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_prettynum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prettynum',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '已占用'), (2, '未占用')], default=2, verbose_name='状态'),
        ),
    ]
