# Generated by Django 3.2.19 on 2023-08-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('count', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=120, upload_to='city/', verbose_name='Logo')),
            ],
        ),
    ]
