# Generated by Django 3.2.8 on 2023-08-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='name',
            new_name='username',
        ),
    ]
